require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/professional_contracts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProfessionalContract. As you add validations to ProfessionalContract, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProfessionalContract.create! valid_attributes
      get professional_contracts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      professional_contract = ProfessionalContract.create! valid_attributes
      get professional_contract_url(professional_contract)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_professional_contract_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      professional_contract = ProfessionalContract.create! valid_attributes
      get edit_professional_contract_url(professional_contract)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProfessionalContract" do
        expect {
          post professional_contracts_url, params: { professional_contract: valid_attributes }
        }.to change(ProfessionalContract, :count).by(1)
      end

      it "redirects to the created professional_contract" do
        post professional_contracts_url, params: { professional_contract: valid_attributes }
        expect(response).to redirect_to(professional_contract_url(ProfessionalContract.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProfessionalContract" do
        expect {
          post professional_contracts_url, params: { professional_contract: invalid_attributes }
        }.to change(ProfessionalContract, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post professional_contracts_url, params: { professional_contract: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested professional_contract" do
        professional_contract = ProfessionalContract.create! valid_attributes
        patch professional_contract_url(professional_contract), params: { professional_contract: new_attributes }
        professional_contract.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the professional_contract" do
        professional_contract = ProfessionalContract.create! valid_attributes
        patch professional_contract_url(professional_contract), params: { professional_contract: new_attributes }
        professional_contract.reload
        expect(response).to redirect_to(professional_contract_url(professional_contract))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        professional_contract = ProfessionalContract.create! valid_attributes
        patch professional_contract_url(professional_contract), params: { professional_contract: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested professional_contract" do
      professional_contract = ProfessionalContract.create! valid_attributes
      expect {
        delete professional_contract_url(professional_contract)
      }.to change(ProfessionalContract, :count).by(-1)
    end

    it "redirects to the professional_contracts list" do
      professional_contract = ProfessionalContract.create! valid_attributes
      delete professional_contract_url(professional_contract)
      expect(response).to redirect_to(professional_contracts_url)
    end
  end
end
