require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/professional_profiles", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProfessionalProfile. As you add validations to ProfessionalProfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProfessionalProfile.create! valid_attributes
      get professional_profiles_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      professional_profile = ProfessionalProfile.create! valid_attributes
      get professional_profile_url(professional_profile)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_professional_profile_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      professional_profile = ProfessionalProfile.create! valid_attributes
      get edit_professional_profile_url(professional_profile)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProfessionalProfile" do
        expect {
          post professional_profiles_url, params: { professional_profile: valid_attributes }
        }.to change(ProfessionalProfile, :count).by(1)
      end

      it "redirects to the created professional_profile" do
        post professional_profiles_url, params: { professional_profile: valid_attributes }
        expect(response).to redirect_to(professional_profile_url(ProfessionalProfile.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProfessionalProfile" do
        expect {
          post professional_profiles_url, params: { professional_profile: invalid_attributes }
        }.to change(ProfessionalProfile, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post professional_profiles_url, params: { professional_profile: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested professional_profile" do
        professional_profile = ProfessionalProfile.create! valid_attributes
        patch professional_profile_url(professional_profile), params: { professional_profile: new_attributes }
        professional_profile.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the professional_profile" do
        professional_profile = ProfessionalProfile.create! valid_attributes
        patch professional_profile_url(professional_profile), params: { professional_profile: new_attributes }
        professional_profile.reload
        expect(response).to redirect_to(professional_profile_url(professional_profile))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        professional_profile = ProfessionalProfile.create! valid_attributes
        patch professional_profile_url(professional_profile), params: { professional_profile: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested professional_profile" do
      professional_profile = ProfessionalProfile.create! valid_attributes
      expect {
        delete professional_profile_url(professional_profile)
      }.to change(ProfessionalProfile, :count).by(-1)
    end

    it "redirects to the professional_profiles list" do
      professional_profile = ProfessionalProfile.create! valid_attributes
      delete professional_profile_url(professional_profile)
      expect(response).to redirect_to(professional_profiles_url)
    end
  end
end
